language: ruby
rvm: "2.1.1"

# to enable javascript testing with X server and firefox
before_install:
  - npm install
  - npm install karma-cli

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate

script:
  - karma start --single-run
  # - bundle exec rspec --format progress
  # - xvfb-run bundle exec cucumber --profile ci

notifications:
  email:
    - bryan.yap.mh@gmail.com
